const conf = {
    policydata: {
        name: "policydata",
        schema: {
           GHEALTH_DATA: { /* table name */
				products: ['ghealth'],
				uniques:['policy_id'],
				array_obj: '',
				repush: true,
                fields: [
			{ name: 'policy_id',type: 'VARCHAR2', size: 100, primary: true, null: "YES", jpath: "policy_id" },
					{ name: 'policynumber',type: 'VARCHAR2', size: 100, null: "YES", jpath: "policy_no" },
					{ name: "endorsementnumber", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "endorsementdescription", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "effectivedate", type: "DATE", fmt:"DD-MM-YYYY", null: "YES", default: "", jpath: "" },
					{ name: "end_date", type: "DATE", fmt:"DD-MM-YYYY hh:mm:ss", null: "YES", default: "", jpath: "policy.policy_end_date_dt" },
					{ name: "entrydate", type: "DATE", fmt:"DD-MM-YYYY hh:mm:ss", null: "YES", default: "", jpath: "policy.policy_start_date_dt" },
					{ name: "empnofamilyid", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "empdependentid", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "membername", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "relationship", type: "VARCHAR2", size: 200, null: "YES", default: "", jpath: "" },
					{ name: "gender", type: "VARCHAR2", size: 100,  null: "YES", default: "", jpath: "" },
					{ name: "dob", type: "DATE", fmt:"DD-MM-YYYY", null: "YES", default: "", jpath: "" },
					{ name: "floatersi", type: "NUMBER", null: "YES", default: "", jpath: "" },
					{ name: "indi_floater_perpersonlimit", type: "NUMBER", null: "YES", default: "", jpath: "" },
					{ name: "individualorfloatersilimit", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "memberlocation", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: ""},
					{ name: "member_id", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: ""},
					{ name: "ageyear", type: "NUMBER", null: "YES", default: "", jpath: "" },
					{ name: "agetypedesc", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "tpacode", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "quote.data.tpa_code" },
					{ name: "tpaname", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "premium_excl_tpa_st", type: "NUMBER", null: "YES", default: "", jpath: "" },
			{ name: "is_migration", type: "VARCHAR2", size: 16, null: "YES", default: "", jpath: "quote.data.is_migration" }
                ]
            },

		GHEALTH_MEMBER_DATA: { /* table name */
                                products: ['ghealth'],
                                uniques:['policy_id','sno'],
                                array_obj: 'proposal.data.gmc_mem',
                                repush: true,
                fields: [
                        { name: 'policy_id',type: 'VARCHAR2', size: 100, primary: true, null: "NO", mandatory: true},
			{ name: 'sno',type: 'NUMBER', null: "NO", jpath:"Sno"},
                                        { name: 'policynumber',type: 'VARCHAR2', size: 100, null: "YES", jpath: "PolicyNumber" },
                                        { name: "endorsementnumber", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "EndorsementNumber" },
                                        { name: "endorsementdescription", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "EndorsementDescription" },
                                        { name: "effectivedate", type: "DATE", fmt:"DD-MMM-YYYY", null: "YES", default: "", jpath: "EffectiveDate (DD-MMM-YYYY)" },
                                        { name: "end_date", type: "DATE", fmt:"DD-MM-YYYY hh:mm:ss", null: "YES", default: "", jpath: "" },
                                        { name: "entrydate", type: "DATE", fmt:"DD-MM-YYYY hh:mm:ss", null: "YES", default: "", jpath: "" },
                                        { name: "empnofamilyid", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "EmpNoFamilyID" },
                                        { name: "empdependentid", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "EmpDependentId" },
                                        { name: "membername", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "Name" },
                                        { name: "relationship", type: "VARCHAR2", size: 200, null: "YES", default: "", jpath: "Relationship" },
                                        { name: "gender", type: "VARCHAR2", size: 100,  null: "YES", default: "", jpath: "Gender" },
                                        { name: "dob", type: "DATE", fmt:"DD-MMM-YYYY", null: "YES", default: "", jpath: "DateofBirth (DD-MMM-YYYY)" },
                                        { name: "floatersi", type: "NUMBER", null: "YES", default: "", jpath: "" },
                                        { name: "indi_floater_perpersonlimit", type: "NUMBER", null: "YES", default: "", jpath: "" },
                                        { name: "individualorfloatersilimit", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "Individual or Floater SI" },
                                        { name: "memberlocation", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "Location"},
                                        { name: "member_id", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "MembershipNo"},
                                        { name: "ageyear", type: "NUMBER", null: "YES", default: "", jpath: "" },
                                        { name: "agetypedesc", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
                                        { name: "tpacode", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "Partycode" },
                                        { name: "tpaname", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
                                        { name: "premium_excl_tpa_st", type: "NUMBER", null: "YES", default: "", jpath: "" }
                ]
            },

			GPA_DATA: { /* table name */
				products: ['gpa'],
				uniques:['policy_id'],
				array_obj: '',
				repush: true,
                fields: [
			{ name: 'policy_id',type: 'VARCHAR2', size: 100, primary: true, null: "YES", jpath: "policy_id" },
					{ name: 'policy_no',type: 'VARCHAR2', size: 100, null: "YES", jpath: "policy_no" },
					{ name: "endorsemet_no", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "endt_description", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "effective_date", type: "DATE", fmt:"DD-MM-YYYY", null: "YES", default: "", jpath: "" },
					{ name: "created_date", type: "DATE", fmt:"DD-MM-YYYY hh:mm:ss", null: "YES", default: "", jpath: "" },
					{ name: "exipry_date", type: "DATE", fmt:"DD-MM-YYYY hh:mm:ss", null: "YES", default: "", jpath: "" },
					{ name: "name_of_the_insured", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "date_of_birth", type: "DATE", fmt:"DD-MM-YYYY", null: "YES", default: "", jpath: "" },
					{ name: "age", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "gender", type: "VARCHAR2", size: 200, null: "YES", default: "", jpath: "" },
					{ name: "nominee_name", type: "VARCHAR2", size: 100,  null: "YES", default: "", jpath: "" },
					{ name: "nominee_age", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "relationship", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "monthly_ctc", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "annual_ctc", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "employee_code", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "personal_accident_sum_insured", type: "NUMBER", null: "YES", default: "", jpath: "" },
					{ name: "individual_medical_sum_insured", type: "NUMBER", null: "YES", default: "", jpath: "" },
					{ name: "active", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "membership_no", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "party_code", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "tpa_code", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "quote.data.tpa_code" },
					{ name: "tpa_name", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "tpa_rate", type: "NUMBER", null: "YES", default: "", jpath: "" },
					{ name: "tpa_premium", type: "NUMBER", null: "YES", default: "", jpath: "" },
					{ name: "gross_premium", type: "NUMBER", null: "YES", default: "", jpath: "" },
					{ name: "client_name", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "designation_grade", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
					{ name: "email_id", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "quote.data.email" },
					{ name: "contact_no", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "quote.data.mobile_no" },
			{ name: "is_migration", type: "VARCHAR2", size: 16, null: "YES", default: "", jpath: "quote.data.is_migration" }
                ]
            },
		GPA_MEMBER_DATA: { /* table name */
                                products: ['gpa'],
                                uniques:['policy_id','sno'],
                                array_obj: 'proposal.data.gpa_mem',
                                repush: true,
                fields: [
                        { name: 'policy_id',type: 'VARCHAR2', size: 100, primary: true, null: "NO", mandatory: true},
			{ name: 'sno',type: 'NUMBER', null: "NO", jpath:"Sno"},
                                        { name: 'policy_no',type: 'VARCHAR2', size: 100, null: "YES", jpath: "PolicyNumber" },
                                        { name: "endorsemet_no", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "EndoNumber" },
                                        { name: "endt_description", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "EndorsementDescription" },
                                        { name: "effective_date", type: "DATE", fmt:"DD-MMM-YYYY", null: "YES", default: "", jpath: "EffectiveDate" },
                                        { name: "created_date", type: "DATE", fmt:"DD-MM-YYYY hh:mm:ss", null: "YES", default: "", jpath: "" },
                                        { name: "exipry_date", type: "DATE", fmt:"DD-MM-YYYY hh:mm:ss", null: "YES", default: "", jpath: "" },
                                        { name: "name_of_the_insured", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "Name" },
                                        { name: "date_of_birth", type: "DATE", fmt:"DD-MMM-YYYY", null: "YES", default: "", jpath: "DateofBirth" },
                                        { name: "age", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "Age" },
                                        { name: "gender", type: "VARCHAR2", size: 200, null: "YES", default: "", jpath: "Gender" },
                                        { name: "nominee_name", type: "VARCHAR2", size: 100,  null: "YES", default: "", jpath: "Nominee Name" },
                                        { name: "nominee_age", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "Nominee age" },
                                        { name: "relationship", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "Relationship" },
                                        { name: "monthly_ctc", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "Monthly CTC" },
                                        { name: "annual_ctc", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "Annual CTC" },
                                        { name: "employee_code", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
                                        { name: "personal_accident_sum_insured", type: "NUMBER", null: "YES", default: "", jpath: "" },
                                        { name: "individual_medical_sum_insured", type: "NUMBER", null: "YES", default: "", jpath: "Sum Insured" },
                                        { name: "active", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "Member Status" },
                                        { name: "membership_no", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "MembershipNo" },
                                        { name: "party_code", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "Partycode" },
                                        { name: "tpa_code", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
                                        { name: "tpa_name", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "" },
                                        { name: "tpa_rate", type: "NUMBER", null: "YES", default: "", jpath: "" },
                                        { name: "tpa_premium", type: "NUMBER", null: "YES", default: "", jpath: "" },
                                        { name: "gross_premium", type: "NUMBER", null: "YES", default: "", jpath: "Premium" },
                                        { name: "client_name", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "Name" },
                                        { name: "designation_grade", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "Designation" },
                                        { name: "email_id", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "Email_ID" },
                                        { name: "contact_no", type: "VARCHAR2", size: 100, null: "YES", default: "", jpath: "Contact_No" }
                ]
            }
			
        }
    }
}
module.exports = conf;
