#server {
#       listen          80;
#       server_name     iscommercialclaims.royalsundaram.net;
#       return 301 https://iscommercialclaims.royalsundaram.net;
#    }

server {
    # nginx listens to this
    listen 80;
    # uncomment the line if you want nginx to listen on IPv6 address
    #listen [::]:80;

    # the virtual host name of this
    server_name rsisghreport.royalsundaram.net;
       access_log      /mnt/ebs1/logs/rsisghreport.server.log main;
       error_page       404 /404.html;
       gzip             on;
       gzip_static      on;
       #gzip_comp_level 1;
       gzip_min_length  1000;
       gzip_proxied     any; # expired no-cache no-store private auth
       gzip_types       text/plain application/xml application/x-javascript appl                                                                                                             ication/javascript text/javascript;
       server_tokens    off;

       #listen          443 ssl;
       #ssl_certificate     /etc/letsencrypt/uat/insillion.royalsundaram.net/rsa                                                                                                             net2022.crt;
       #ssl_certificate_key /etc/letsencrypt/uat/insillion.royalsundaram.net/rsa                                                                                                             net2022-encrypted.key;
       ssl_protocols       TLSv1.2 TLSv1.3;
       ssl_ciphers         HIGH:!aNULL:!MD5;


    #auth_basic "Protected";
    #auth_basic_user_file passwords;

    location /api/ {
        gzip_static on;
        #index  index.html;
        #root /mnt/ebs1/rsclaims/insync/public;

        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:9097;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
    }
    location / {
        gzip_static on;
        root /mnt/ebs1/rsisghu/insync/public;
        try_files $uri $uri/ /index.html =404;
    }

}
